# Generated by Django 3.0.3 on 2020-02-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Idea',
        ),
    ]
